### PR TITLE
 added stars and two types of review (imdb, user) 

### PR DESCRIPTION
**Pull request by divyanshsingh101**
[added stars for api fetched rating and added form , for user rating and added user rating :)

### CODE REVIEW

**Comment by eleensmathew** [comment]
38 commits? can you close this pr and make a new one but only with your new commits?

**Comment by eleensmathew** [comment]
Also pls make a pr for the contrihub org and not my repo.

**Comment by eleensmathew** [comment]
PLease make the pr in contrihub org. Im closing this pr here

**Comment by divyanshsingh101** [comment]
Yes ma'am I have made a pr there

**Pull request closed without merging**
